### ISSUE TITLE
Makefile Generic rule

### ISSUE THREAD

**Issue by kontrafiktion** [box-cutter/ubuntu-vm#38]
The Makefile contains quite a lot of repetition, the generic rule is explicitly marked as "not used currently".

The only difference between the invocations (just looking at the vmware ones) seems to be this:

     -var "iso_url=$(UBUNTU1004_SERVER_I386)"
     -var "iso_url=$(UBUNTU1004_SERVER_AMD64)"
     ...

a very simple solution would be to define a local directory (e.g. "isos") and to use `iso_urls` instead of `iso_url` inside the templates like this:

        "iso_urls": ["isos/{{user `iso_name`}}", "http://releases.ubuntu.com/14.04/{{user `iso_name`}}"],

The iso_name can be set inside the `variables` section of the template

The only downside I can see is the hardcoded location of the `isos` directory -- but even that could be made configurable

**Comment by annawake** [comment]
Done
