### ISSUE TITLE
no more pre-built machines?

### ISSUE THREAD

**Issue by jrgifford** [box-cutter/ubuntu-vm#42]
I use these personally and professionally. What would it take/who do I need to talk to about providing hosting/sponsorship for pre-built versions?

**Comment by mathewpeterson** [comment]
I use these machines quite a bit and would also like to help support pre-built versions.

**Comment by jrgifford** [comment]
I can build VMWare & VirtualBox machines, unfortunately I don't have the ability to make parallels machines.

**Comment by mathewpeterson** [comment]
Me as well.

**Comment by mathewpeterson** [comment]
@misheska Can you provide any feedback?

**Comment by misheska** [comment]
I just switched jobs and no longer have employer-sponsored hosting for the built boxes.  I’m not willing to foot the monthly bill on my own, and I’m looking for a new place to store the built binaries and to hopefully make them available once more.

That being said, no matter what, box-cutter will live on as an open source project.  I still need the templates for many things that I do, so I will be keeping them up-to-date.  The only question is whether or not there will be free binaries available for download.

**Comment by jrgifford** [comment]
So we're offering to investigate storing the binaries. Can you drop us
an email with the costs, and then we can suggest it to our respective
employers?

**Comment by annawake** [comment]
SmartyStreets is now providing hosting for the pre-built boxes.  The boxes should be repopulated through the cdn and atlas in a few days.

**Comment by mathewpeterson** [comment]
Thank you @annawake! I am still worried that we will run into situations similar to this in the future. 

What happens if SmartyStreets decides it no longer wants to support box-cutter?

**Comment by misheska** [comment]
The future is uncertain and there are no guarantees for something that is being provided for free, not much I can do about that ;-)  We'll cross that bridge when we come to it.  The SmartyStreets folks have promised to give some advanced notice if they are no longer willing (or able) to provide support.  However, they are avid users of box-cutter and pitched in to make sure these boxes were still around for them to use as well as for everyone else.  I'm really grateful for their support!
